<?php
return array (
  'DB_HOST' => '127.0.0.1',
  'DB_NAME' => 'cms1',
  'DB_USER' => 'root',
  'DB_PWD' => '',
  'DB_PORT' => '3306',
  'DB_PREFIX' => 'jkd_',
  'SITE_TITLE' => 'CMS管理系统',
  'SITE_URL' => 'http://localhost/cms1/',
  'GOLBAL_SEO_K' => '企业管理系统',
  'GOLBAL_SEO_D' => '',
  'SITE_NAME' => '',
  'ICP' => '',
  'EMAIL' => '',
  'TEL' => '',
  'FAX' => '',
  'QQ' => '',
  'ADDRESS' => '',
  'COOKIE_PATH' => '/',
  'COOKIE_PREFIX' => '',
  'TMPL_L_DELIM' => '{jkd_',
  'TMPL_R_DELIM' => '}',
  'APP_AUTOLOAD_PATH' => '@.ORG',
  'IS_MOBILE' => '1',
  'IS_DEBUG' => '1',
  'IS_DEVELOPER' => '1',
  'IS_TPL_MANAGE' => '1',
);
?>